server:
  servlet:
    context-path: /hst-backend

spring:
  application:
    name: hsts
  datasource:
    url: jdbc:postgresql://localhost:5432/hstdb
    username: userhst
    password: pwdhst
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
  #
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.springframework.web.servlet.DispatcherServlet: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      com.seuprojeto: DEBUG
  mvc:
    log-request-details: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

